services:
  strata-scraper:
    build: .
    container_name: strata-scraper
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./scraped_sites:/app/scraped_sites
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=False
      - FLASK_ENV=production
      - USE_DYNAMODB=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
