services:
  strata-scraper:
    build: .
    container_name: strata-scraper-prod
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - FLASK_ENV=production
      - DEBUG=False
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    profiles:
      - production
