version: '3.8'

services:
  strata-scraper:
    build: .
    container_name: strata-scraper
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=False
      - FLASK_ENV=production
      - USE_DYNAMODB=true
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=gambix-strata-production
      - S3_ENDPOINT_URL=https://s3.amazonaws.com
      - DYNAMODB_TABLE_PREFIX=gambix_strata_
    volumes:
      - ./logs:/app/logs
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials (read-only)
      - /etc/passwd:/etc/passwd:ro  # For IAM role access
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - default
      - production

  # Development profile with local storage
  strata-scraper-dev:
    build: .
    container_name: strata-scraper-dev
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=True
      - FLASK_ENV=development
      - USE_DYNAMODB=false
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./scraped_data:/app/scraped_data
    restart: unless-stopped
    profiles:
      - development
